# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.
#
# ,--------.      ,--.   ,--. ,--.
# '--.  .--',---.  \  `.'  /,-'  '-.
#    |  |  | .-. :  .'    \ '-.  .-'
#    |  |  \   --. /  .'.  \  |  |
#    `--'   `----''--'   '--' `--'
theme: jekyll-text-theme
text_color_theme: default #eg: default | dark | forest | ocean | chocolate | orange
## Base settings ##
url: https://www.weigao.cc #the base hostname & protocol for your site e.g. https://www.someone.com
baseurl: /
title: NERCHE
description: > #this means to ignore newlines until "nav_lists:"
  Weigao's Blog

nav_lists:
  - titles:
      en: About
      zh: 关于
      zh-Hans: 关于
      zh-Hant: 關於
    url: /about

paths:
  base: /blog
  home: /
  all:  /blog/all.html
  rss:  /feed.xml

## GitHub repository (if the site is hosted by GitHub) ##
repository: chenweigao/chenweigao.github.io  #e.g. someone/someone.github.io
repository_tree: master #e.g. master

## Language & timezone ##
lang: en #the language of your site, eg: en(English), zh(简体中文), zh-Hans(简体中文), zh-Hant(繁體中文)
timezone: Asia/Shanghai #see https://en.wikipedia.org/wiki/List_of_tz_database_time_zones for the available values

## Author & social ##
author:
  name: Weigao Chen
  email: mail@weigao.cc #your Email address e.g. someone@site.com
  # facebook:  #your Facebook username
  # twitter:  #your Twitter username
  github: chenweigao #your GitHub username
  # googleplus:  #your Google+ username
  # weibo:  #your Weibo username
  # douban:  #your Douban username
  # linkedin:  #your Linkedin username

## TOC
toc:
  # selectors: 'h1,h2,h3'

## Comment system (Disqus) ##
# disqus:
#   shortname: weigao #the Disqus shortname for the site

# Comment system (gitalk) ##
# please refer to https://github.com/gitalk/gitalk for more info.
gitalk:
  clientID: d0b1e8734e879665dfc5 #Github Application Client ID
  clientSecret: 9eaf06b6821fc117284c4d555ee43287f0f7bd04 #Github Application Client Secret
  repository: gitalk #Github repo
  owner: chenweigao #Github repo owner
  admin: #Github repo owner and collaborators, only these guys can initialize github issues, IT IS A LIST.
    - chenweigao

## Google Analytics ##
ga_tracking_id: UA-119753118-1 #Google analytics id for the site

## Reading quantity (LeanCloud) ##
# leancloud:
#   app_id: wJrq8Ck2MqeaFzOYUf0TcP6G-gzGzoHsz #LeanCloud App id
#   app_key: taRHm1fEce4nGp2lmNgkiW9U  #LeanCloud App key
#   app_class: blog #LeanCloud App class

# mathjax: true
# mathjax_autoNumber: true
# mermaid: true
# chart: true

## Paginate ##
paginate: 7
paginate_path: /blog/page:num

## Post excerpts ##
excerpt_separator: <!--more-->
excerpt_type: html # text | html

## Sources ##
sources: unpkg #eg: bootcss | unpkg

## Build ##
markdown: kramdown
highlighter: rouge
permalink: date

exclude:
  - CHANGELOG.md
  - CHECKLIST.md
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README-*.md
  - README.md
  - gulpfile.js
  - jekyll-text-theme.gemspec
  - package-lock.json
  - package.json
  - /docs
  - /node_modules
  - /screenshots
  - /test
  - /vendor

## Plugins ##
plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jemoji

## Server ##
server_url: "0.0.0.0"
